-- H2 schema generated from Oracle
-- Generated at Thu Mar 05 21:45:24 WET 2026

CREATE TABLE EMP (
  EMPNO NUMERIC(4) NOT NULL,
  ENAME VARCHAR(10),
  JOB VARCHAR(9),
  MGR NUMERIC(4),
  HIREDATE TIMESTAMP,
  SAL NUMERIC(7,2),
  COMM NUMERIC(7,2),
  DEPTNO NUMERIC(2)
  ,  CONSTRAINT PK_EMP PRIMARY KEY (EMPNO)
);

CREATE TABLE DEPT (
  DEPTNO NUMERIC(2) NOT NULL,
  DNAME VARCHAR(14),
  LOC VARCHAR(13)
  ,  CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO)
);

CREATE TABLE BONUS (
  ENAME VARCHAR(10),
  JOB VARCHAR(9),
  SAL NUMERIC,
  COMM NUMERIC
);

CREATE TABLE SALGRADE (
  GRADE NUMERIC,
  LOSAL NUMERIC,
  HISAL NUMERIC
);

ALTER TABLE EMP ADD CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO);
